#!/usr/bin/env php
<?php

use Symfony\Component\DependencyInjection\ContainerBuilder;
use TestsAlwaysIncluded\SymfonyConsoleBootstrap\Application;

$applicationRoot = dirname(__DIR__);
$vendorRoot = $applicationRoot . DIRECTORY_SEPARATOR . 'vendor' . DIRECTORY_SEPARATOR;

//Require the vendor autoloader for dependencies
require_once $vendorRoot . 'autoload.php';
require_once 'AppBoot.php';

//Create the Bootstrap app specific class
$bootstrap = new AppBoot();

//Create the application
$application = new Application($bootstrap);

//Boot the application
$application->boot($applicationRoot);

//Run the application
$application->run();
